spring.application.name=employee-case-Study

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.default_schema=defaultdbname

spring.datasource.hikari.maximumPoolSize=50
spring.jpa.open-in-view=false